version: '3'
services:
  raycast-unblock:
    image: wibuswee/raycast-unblock:latest
    container_name: raycast-unblock
    hostname: raycast-unblock
    restart: always
    command: >
      --ai_key=your-open-ai-key
      --openai_base_url=https://api.openai.com
      --ai_type=openai
      --host=0.0.0.0
    ports:
      - "3000:3000"